# Generated by Django 3.0.8 on 2020-07-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1, null=True),
        ),
    ]
