# Generated by Django 3.0.7 on 2020-06-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='emaill',
            new_name='email',
        ),
    ]
