# Generated by Django 3.0.7 on 2020-06-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200616_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='create_at',
        ),
    ]
