# Generated by Django 3.0.7 on 2020-07-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200701_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='change_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
