# Generated by Django 3.0.7 on 2020-07-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20200713_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='change_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
