# Generated by Django 3.0.8 on 2020-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
            ],
        ),
    ]
